[book]
title = "rlevo: Contributor Guide"
description = "A guide specifically for developers and contributors with Rust experience."
authors = ["Anthony Torlucci"]
language = "en"
src = "src"
text-direction = "ltr"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/anthonytorlucci/rlevo"
edit-url-template = "https://github.com/anthonytorlucci/rlevo/edit/main/docs/contributor-book/{path}"
mathjax-support = false
