mod commands;

use tracel_xtask::prelude::*;

#[macros::base_commands]
pub enum Command {
    /// Run every crate's default test set — the pull-request gate.
    TestFast(commands::test_fast::TestFastCmdArgs),
    /// Run the CPU-bound `#[ignore]`d long tests the fast tier skips.
    TestHeavy(commands::test_heavy::TestHeavyCmdArgs),
}

// todo! test-gpu command

fn main() -> anyhow::Result<()> {
    let (args, environment) = init_xtask::<Command>(parse_args::<Command>()?)?;
    let context = args.context.clone();
    match args.command {
        Command::TestFast(cmd_args) => {
            commands::test_fast::handle_command(&cmd_args, environment, context)
        }
        Command::TestHeavy(cmd_args) => {
            commands::test_heavy::handle_command(&cmd_args, environment, context)
        }
        // dispatch_base_commands function is generated by the commands macro
        _ => dispatch_base_commands(args, environment),
    }
}
